package co.arichardson.gradle.make.internal

import co.arichardson.gradle.make.ExternalNativeTestExecutableSpec

class DefaultExternalNativeTestExecutableSpec extends DefaultExternalNativeExecutableSpec implements ExternalNativeTestExecutableSpec {
}
